<template>
  <div class="uiv">
    <btn-toolbar>
      <btn-group>
        <btn>1</btn>
        <btn>2</btn>
        <btn>3</btn>
        <btn>4</btn>
      </btn-group>
      <btn-group>
        <btn>5</btn>
        <btn>6</btn>
        <btn>7</btn>
      </btn-group>
      <btn-group>
        <btn>8</btn>
      </btn-group>
    </btn-toolbar>
  </div>
</template>
