'use strict'

import hljs from 'highlight.js/lib/highlight'

/**
 * These are for client side usage. not related to posts (which generated by server)
 */

hljs.registerLanguage('xml', require('highlight.js/lib/languages/xml'))
// hljs.registerLanguage('bash', require('highlight.js/lib/languages/bash'))
// hljs.registerLanguage('coffeescript', require('highlight.js/lib/languages/coffeescript'))
hljs.registerLanguage('css', require('highlight.js/lib/languages/css'))
// hljs.registerLanguage('markdown', require('highlight.js/lib/languages/markdown'))
// hljs.registerLanguage('http', require('highlight.js/lib/languages/http'))
// hljs.registerLanguage('java', require('highlight.js/lib/languages/java'))
hljs.registerLanguage('javascript', require('highlight.js/lib/languages/javascript'))
// hljs.registerLanguage('json', require('highlight.js/lib/languages/json'))
// hljs.registerLanguage('less', require('highlight.js/lib/languages/less'))
// hljs.registerLanguage('php', require('highlight.js/lib/languages/php'))
// hljs.registerLanguage('python', require('highlight.js/lib/languages/python'))
// hljs.registerLanguage('scss', require('highlight.js/lib/languages/scss'))
// hljs.registerLanguage('sql', require('highlight.js/lib/languages/sql'))
// hljs.registerLanguage('yaml', require('highlight.js/lib/languages/yaml'))

export default hljs
