name: publish doc

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          fetch-depth: 0
          ref: dev
      - uses: actions/setup-node@v6.5.0
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v6.0.9
        with:
          version: 11.13.0
          run_install: true
      - name: Build
        run: pnpm run docs:build
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_branch: gh-pages
          build_dir: docs/.vitepress/dist
          jekyll: false
