name: publish npm

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-node@v7.0.0
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v6.0.10
        with:
          version: 11.21.0
          run_install: true
      - name: Build dist
        run: pnpm run dist
      - name: Publish NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
